// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // default docs
    },
    {
      type: 'autogenerated',
      dirName: 'documents', // loads all markdowns from /docs/documents
    },
  ],
};

export default sidebars;
